apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zi5jkvjuv-python 
  janus-idp.io/tekton: zi5jkvjuv-python
  backstage.io/kubernetes-id: zi5jkvjuv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zi5jkvjuv-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  